version: "3.4"
services:

  datadog:
    image: gcr.io/datadoghq/agent:latest
    ports:
      - 8126:8126/tcp
      - 8125:8125/udp
    environment:
     - DD_API_KEY=${DD_API_KEY}
     - DD_HOSTNAME=james-laptop
     - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
